[tool]
uv = "0.1.42"

[project]
name = "gemini-agent"
version = "0.1.0"
description = "A2A wrapper for Gemini API integration"
dependencies = [
    "google-generativeai>=0.5.4",
    "fastapi>=0.111.0",
    "uvicorn>=0.30.1"
]
